### ISSUE TITLE
[QUESTION] Custom Scripts and Overlays

### ISSUE THREAD

**Issue by wcphart** [Firebottle/Firebot#182]
So, with the addition of custom scripts (omg excited!) is it possible the Firebot run component could be driving another html component in the same dir to be added as an overlay in the stream?

Like the Firebot run component, access public methods in my personal component that is doing html'y things based on its logic?

omg so many ideas in my head if so.....

**Comment by Firebottle** [comment]
Heya, take a look at the writing scripts wiki page to get an idea of how it works. If you still have questions after that just let us know.

https://github.com/Firebottle/Firebot/wiki/Writing-Custom-Scripts

**Comment by ebiggz** [comment]
If your personal component would work with node.js, I believe you should be able to require it into the custom script as long as you get the file path in correct. Otherwise, you could have your personal component host api endpoints that the custom script could call to. I know other folks have used the latter approach. 😃

**Comment by wcphart** [comment]
@Firebottle Thats what drove me to my question. @ebiggz Exactly, I was imagining my React app interfacing with a hosted script that manages an overlay, which could all be driven by Firebot buttons....

So, this is pretty awesome stuff!! Very excited!

**Comment by wcphart** [comment]
Closing, as my questions were answered, thanks!
