### ISSUE TITLE
User or Group Specific button presses

### ISSUE THREAD

**Issue by GamertagIsAnt** [Firebottle/Firebot#189]
Can we get a button effect that allows us to have a specific user or group of users able to press a button? I apologize if there already is this option. I seen we have the option to Change Group as an effect as a button click but I didn't know if that was the same thing or not.

**Comment by Firebottle** [comment]
Right now that would result in everyone being able to see the button but it would only work for certain people. This causes more problems than it fixes because people think the button is broken. 

So just make two scene that have the same buttons and then only show the unique buttons to certain groups.

Everything you need is in the app but it works a bit different than your thinking.

**Comment by GamertagIsAnt** [comment]
alright, only reason I was asking was for Kills loses and Chicken dinners on a pubg board but still allowing others to use the main soundboard since when you switch scenes it changes for everyone. just means I will have to make 15 scenes for alternate users or subs Thanks for the heads up

**Comment by GamertagIsAnt** [comment]
I think ill just have to leave user specific buttons alone until they allow us to duplicate scenes in mixer, that's way to much work. lol
