### ISSUE TITLE
Button configuration save

### ISSUE THREAD

**Issue by ThePerry-2015** [Firebottle/Firebot#25]
The last change to the button form validation made some weird animations when saving button settings. Sometimes it animates it just nicely away and other times it just pushes you back to the "Start" page of the application with a white flash.

**Comment by Firebottle** [comment]
I *think* I might have fixed this by only validating forms on submit instead of keypress, onfocus, etc... I think the issue was that some actions caused the validation to lock up. When this happened it refreshed the HTML to try to get it running again.

Can you test and see how it works for you with the newest commit?

**Comment by ThePerry-2015** [comment]
This seems to work a lot better yes.. :)
