### ISSUE TITLE
user settings folder???????

### ISSUE THREAD

**Issue by crossfire151** [Firebottle/Firebot#302]
#### Describe your issue or feature request (details are helpful!):

WTF is the user settings folder?????
More information please!!!!!

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Great job on this bug report, it really gives us a good amount of information to help you out. You can get to the user-settings folder by going to the settings area of Firebot and clicking the "open root folder" button.

I'm closing this because you didn't actually enter an issue. You just shouted a bit.
