### ISSUE TITLE
Video Staying On Screen When Finished Playing

### ISSUE THREAD

**Issue by xKells** [Firebottle/Firebot#350]
[2017-09-07.zip](https://github.com/Firebottle/Firebot/files/1285024/2017-09-07.zip)

[2017-09-07.zip](https://github.com/Firebottle/Firebot/files/1285021/2017-09-07.zip)

#### Describe your issue or feature request (details are helpful!): When a video stops playing it will stay on screen until a new video is played.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running? 4.1.0

- What are the steps to reproduce the issue?
1) Reload the browser source 
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by ThePerry-2015** [comment]
Can you attach a zip of the overlay directory inside the firebot-data directory?
When I test your board setup on my end with Firebot 4.1.0 the videos fade in and out just like they are supposed to do.

**Comment by xKells** [comment]
[overlay.zip](https://github.com/Firebottle/Firebot/files/1285340/overlay.zip)

**Comment by ThePerry-2015** [comment]
What's the URL/filepath for the firebot overlay browser source in OBS?
I'm still not able to get it to show the issue you have with video files even if I use you overlay files.

Are you using Settings -> Overlay -> Overlay Compatibility -> OBS or Other?

**Comment by xKells** [comment]
C:\Users\StreamPC\AppData\Roaming\Firebot\firebot-data\overlay\firebot.html
I have it set to OBS

**Comment by ThePerry-2015** [comment]
Have you tried removing the overlay and putting it back in?
I'm not able to duplicate your issue with the same settings as you use.

The only other thing I can suggest now is: https://github.com/Firebottle/Firebot/wiki/Troubleshooting-Firebot-Overlay-issues-in-OBS-Studio
And check if the console there can shed some light on the issue.

I just tested with OBS here: https://streamable.com/zc3bx
Firebot failed to connect to Mixer due to using your board without having access to use it, but it's the same if triggered within the bot or from the interactive panel on Mixer so that shouldn't cause the issue.

**Comment by xKells** [comment]
Let me try that and message you back

**Comment by Firebottle** [comment]
Going to go ahead and close this since it's been over a week. Just comment on this thread or make a new one if you're still having the issue.
