### ISSUE TITLE
Chroma key on video? 

### ISSUE THREAD

**Issue by awrebels** [Firebottle/Firebot#351]
#### Describe your issue or feature request (details are helpful!):

Do you think it would be possible to add a chroma key feature to the video effect? I've put the chroma key on the firebot overlay in obs but any firebot videos that are simultaneous will cut into one another usually resulting in the lower being cutoff or hidden. 

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by kateract** [comment]
It might be possible, but would probably take a while and might not be consistent across the video types.  I found [this](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Manipulating_video_using_canvas) that describes how to use chroma key on video tag objects, but not sure this will work out with say, embedded youtube videos.

**Comment by ebiggz** [comment]
Hey @awrebels  
After a lot of trail and error and investigation, v4.2.2 hopefully has a solution that will work for you. 
Naively supporting chroma key would of been difficult due to javascript security policies not allowing html canvases from viewing, altering, and displaying videos or images saved locally on a computer. 

So we implemented an alternative solution, Firebot now allows you to define multiple "overlay instances". Each instance you create will have its own unique URL that you can put into OBS as a browser source. For each video effect, you can define which instance you want it to show up on. So you could create a "Chroma" overlay instance (that you apply the chroma key effect to in OBS), and send all your videos that need to be chroma key'd there. And then let your other videos and images that dont need chroma key stay on the main instance that doesnt have the chroma key effect applied. 

I tested stacking multiple videos that used chroma key on top of each other and they seemed to work great. Let me know if you have any issues or questions about this.

**Comment by awrebels** [comment]
Exceptionally fantastic work - excited to try it out. You deserve a parade in your honor! I hope you will settle for a digital one of these things 🎉

**Comment by ebiggz** [comment]
@awrebels Haha thanks! 

I updated the wiki with info about the new overlay instances, should get you started
https://github.com/Firebottle/Firebot/wiki/Advanced-Uses#overlay-instances
