### ISSUE TITLE
.AVI files as a video source

### ISSUE THREAD

**Issue by TVCalico** [Firebottle/Firebot#386]
#### Describe your issue or feature request (details are helpful!):

Hey there. I may be a total scrub but in lieu of having after effects, I'm using sony vegas to make AVI videos that treat my "green screen" videos as transparent for the videos I'd like to play in my commands.
Consider making .AVI files a compatible source. I'm at "TVCalico" on mixer if you want me to clarify anything. Thanks!

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

- What are the steps to reproduce the issue?
1)
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by ebiggz** [comment]
Hi TVCalico! 

Since the overlay is an HTML file, the only video file types we can support are ones officially supported HTML 5. Those being MP4, WebM, Ogg. The most common being mp4. 

To support other video formats, we would have to implement a custom video player which we may consider down the road but aren't going to right now.

The good news is, you can still accomplish green screen effects though. You can do this by exporting your videos as mp4 with the green sceen background present. Then follow the steps [here ](https://github.com/Firebottle/Firebot/wiki/Advanced-Uses#overlay-instances)to enable "Overlay Instances". This will let you have two overlays in your broadcasting software. One overlay will contain all things that don't require chroma key, and the second you can send all your greenscreen videos to. Then in your broadcasting software, you can have it apply the chroma key effect in real time. :)

**Comment by TVCalico** [comment]
Hey! Thanks for replying. I actually found that out in "Advanced Uses" after further inspection.
Glad your description put me on the same page though. Thanks!
