### ISSUE TITLE
Unable to Re-Install Firebot

### ISSUE THREAD

**Issue by DS-Synchro** [Firebottle/Firebot#414]
#### Describe your issue or feature request (details are helpful!):

This is probably the weirdest issue ever. I've been using Firebot for maybe two weeks. No issues. But then one afternoon I got a Windows 10 message stating I didn't have the correct program to open "this file". The file being the launcher for Firebot. Several full PC restarts later I attempted to reinstall Firebot but everytime I do it says "Installation has failed: There was an error while installing the application. Check the setup log for more information and contact the author." I'm given two options: Close or Open Setup Log. Neither help me in any way.

-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?
Version 4.4.3

- What are the steps to reproduce the issue?
1) Opening Firebot.exe or Firebot installer
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by Firebottle** [comment]
Have you tried uninstalling Firebot completely and then reinstalling it?

**Comment by DS-Synchro** [comment]
Yeah. It's no longer installed but when I attempt to reinstall I get "Installation has failed: There was an error while installing the application. Check the setup log for more information and contact the author."

**Comment by Firebottle** [comment]
If you try to run the setup as admin does that make any difference?

**Comment by DS-Synchro** [comment]
Nope. Same error. Would you like me to attach the Setup Log it supplies after the error?

**Comment by DS-Synchro** [comment]
I guess support for this thread has been abandoned. I'll just remove all files and use a different program.

**Comment by sorryaboutyourcats** [comment]
I had a similar issue - all I did was install it as a different user [shift + right click, run as different user], then made a batch to just run Firebot as said user each time; I'm sure there might be a cleaner way to do it, but it was the quickest solution at the time for me.

Regardless, if you need further assistance on how to achieve that, just slide into my DMs DS. =P

**Comment by DS-Synchro** [comment]
@sorryaboutyourcats I ever told I freaking love you dude? Did what you said and it works! <3

**Comment by ebiggz** [comment]
@DS-Synchro Omg I apologize for the delay, I just noticed this. Somehow it got lost in the fray. I am really glad @sorryaboutyourcats had a slick workaround because I haven't heard of this issue before and I wouldn't have known a workaround, thanks for that man! DS - if you have anymore issues please let us know. If you have discord, you can also toss questions in here: discord.gg/DegW792. We are more likely to catch the question there plus the whole community can chime in with ideas and help too. :)

**Comment by dylanbaumann** [comment]
This thread has been closed for nearly a year, however I recently ran into this issue on the latest release. Installing as an alternate user is a slick work-around, but I do not have multiple users on this computer, nor do I wish to create any. Luckly I made a work around which worked for me personally, so I want to post this here in case any others stumbled across this thread with the same issue in the future.

### How I ran into the issue on windows 64bit:
I ran into this issue recently as well after installing Firebot and connecting my account + boards. I had turned on the connection between Firebot and Mixer to test the buttons out, then closed the program. I then moved the Setup and Firebot shortcut icon to my trash. Upon relaunching the app had linked issues (likely due to the move to trash), but restoring their location didn't fix this. 

I then tried to just reinstall it via the latest download (v4.11.5 at the time), but ran into the issue which was posted above with "Installation Has Failed" error happening regardless of Admin privileges, etc. 

### Work Around
1. Open your Window Search and type in "%appdata%" and hit enter
2. Go to the `/username/appdata/` folders and remove everything regarding Firebot
3. Empty your trash to ensure the appdata folders are fully removed
4. Restart your computer to clear any remaining connections which could inhibit Firebot from reinstalling
5. Re-download the [latest version](https://crowbartools.com/tools/firebot/)
6. Run the installation as administrator (just in case).
