### ISSUE TITLE
I want this for mac

### ISSUE THREAD

**Issue by aidentab** [Firebottle/Firebot#428]
#### Describe your issue or feature request (details are helpful!):

I NEED THIS FOR MAC
-----------------------------------------------------------------------
#### If you're reporting an issue, *please* fill out & do the following:

- What version of Firebot are you running?

I CAN"T
- What are the steps to reproduce the issue?
1) HIT DOWNLOAD
2)
3)

- (IMPORTANT) Go to Firebot's root folder (**Settings tab -> Open Root Folder**) then zip the following two files and attach that zip to this issue:

1) In **user-settings > controls**, find the .json file with the name of the board you are having issues with.
2) In **user-settings > logs**, find the latest log file.
I CAN'T BECAUSE I DON'T HAVE IT

```
NOTE: A lot of issues can be solved by,
- Updating to the latest version
- Trying the troubleshooting steps on the wiki
```

**Comment by SReject** [comment]
Our current development team does not have a Mac/iOS environment to test against, so sadly this is not currently possible.

If anyone reading this has the technical know-how of working with Electron and Angular that would be interested in bringing Firebot to Mac/iOS, please contact us on [discord](https://discord.gg/7dbZj2p)

**Comment by NightmareJoker2** [comment]
@Firebottle You know, if you don't want my help with this, and by proxy with https://github.com/Firebottle/Firebot/issues/375#issuecomment-335160810 you could've just said so, instead of doing what you repeatedly, and incorrectly accused me of (feel free to consult a modern dictionary, if you're confused). I am disappointed in your actions.
