### ISSUE TITLE
Feature Request: Move sound-files into the directory structure of the bot?

### ISSUE THREAD

**Issue by ThePerry-2015** [Firebottle/Firebot#43]
I've not looked into this yet, but I think it should be possible with the fs module to move/copy the selected sounds into the directory structure of the bot inside the user-settings part. This would make it pretty hard to lose a sound file just because you accidentally removed the sound from your download folder when you cleared it all out because it was cluttered with all kinds of stuff.

Ahemm, this totally hasn't happened to me.. xD

**Comment by Firebottle** [comment]
I don't know if this is a feature we really need to add. It adds an extra layer of complexity to the app, and it makes it a bit more confusing for users. I think it'll cause more problems than it solves. 

Example: Someone overwrites a sound file they already have loaded up. It doesn't change because we're actually using one we copied when they first set up the button. Does the app try to re-fetch and copy that sound each time someone hits a button? Do we tell the user to restart and then grab it again on app restart? Or do we tell them to abandon the library of sounds they have and work out of the bot folder?

I'm going to go ahead and close this, but I'll make a note on my list to look at it again later.
