### ISSUE TITLE
Read text from text file.

### ISSUE THREAD

**Issue by Avid-Gamer** [Firebottle/Firebot#460]
I would like the ability to write more information to files as well as read information from files. I want it to be in variable form like ankhbot/chatbot where you type $(writefile[C:\location\filename.txt]) or make the GUI just super user friendly.

**Comment by Firebottle** [comment]
Hello! You can already write information to a text file using the built in effects. You could also read text from a file using the built in custom script system.

I can leave this feature request open for possibly implementing a "read text" effect.

**Comment by ebiggz** [comment]
A use case/example of how you'd like to use this would be helpful too. :)

**Comment by ThePerry-2015** [comment]
Reading track info from Pretzel to make it available on a button or chat command.

**Comment by Avid-Gamer** [comment]
@Firebottle Yes please make the Read Text effect since you now have Write to File effect which I didn't see a few weeks back. I have been experimenting with other bots in the mean time, but your bot has the potential to be the complete package.

**Comment by ebiggz** [comment]
Release in v4.8.0

**Comment by Canthealz** [comment]
Hey all, is there any way to get the Write to text file to update live? where i wouldn't have to close and reopen the text file for it to update? not sure if that a possible thing.

Here's what im working on... I have buttons with heroes on my stream and when a viewer clicks on it it puts that heroes name into a text file so that i can have an on going list of what hero the viewers would like to see played, but I'm having to close and reopen to get an updated list.

**Comment by DragynsLair** [comment]
How are you putting the text to the screen?  There is usually an option to poll the file in the stream software.

For example... In OBS you use "Read From File" and then add the text file as the source.

**Comment by Canthealz** [comment]
Im not putting the text onto the stream via an overlay. I have interaction buttons on my Mixer Stream that when they click on them they play a sound file and write the name of the hero they chose to a text document... was wondering if there was a way to get that text document to update in real time and not have to close and reopen when a viewer selects a hero.

**Comment by DragynsLair** [comment]
The document is updating in real time.  The problem is that whatever you're
using to view it isn't.  (I'm guessing you're using notepad or something
similar).  That isn't really a Firebot issue.

You can use notepad++ and follow the instructions at this link to
potentially get the result you're looking for:
https://stackoverflow.com/questions/36718907/refresh-document-in-notepad

**Comment by SinaCutie** [comment]
Is there a "Read from text file" that can be used by a command? I'd like to read a file and output the text to the chat, not through an overlay.
