### ISSUE TITLE
Modification loop spark cost

### ISSUE THREAD

**Issue by Firebottle** [Firebottle/Firebot#500]
Apparently spark costs are not being updated appropriately during the modification loop for some people.

**Comment by ebiggz** [comment]
I suspect this happens when the user resync’s their board. When they do that, anything they edited locally (name, text, sparks, tooltip) will get wiped and be replaced by whatever is saved on the dev lab. Ideally we need a way to check if a button has changed on the devlab and only update it locally if it has.
