### ISSUE TITLE
Constent Loading Not Allowing Streamer or Bot Login

### ISSUE THREAD

**Issue by TopStiGear** [Firebottle/Firebot#600]
## What version of Firebot are you running?

4.10.5

## Please describe the issue or feature requests in as much detail as possible.

Ever since the last Mixer chat problem logged my Streamer and Bot accounts out of Firebot I am unable to log back in and get an endless loading circle whenever I try. (Have rebooted pc aswell as program several times)
Edit.... More info: It askes me to log in which I do, then authorize the bot to access my Mixer account that window then closes and I have a yellow loading circle above the Manage Logins window unable to click anything in the program and it never loads to say the Streamer or Bot account is connected dependent on which I have tried to log into.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Hi @TopStiGear are you still experiencing this issue?

The most common cause for this is the file where we save your account has become corrupted, and the fix is just to delete it and re-sign into your accounts.

To do this: Open Firebot > Settings > Open Root Folder > /user-settings > look for auth.json and delete it > Restart Firebot

**Comment by Firebottle** [comment]
Closing as it's been 18 days with no response.
