### ISSUE TITLE
Buttons that access user selected/created APIs

### ISSUE THREAD

**Issue by WeiseCreations** [Firebottle/Firebot#87]
As a user with development experience, I would like to be able to add my own API to a button to, for example, use YouTube's API to prompt the person clicking this button to subscribe to my channel. Or follow on Twitter, or tweet a tweet out (similar to share & embed button but without so many clicks).

You can implement this yourself, but why not allow us to use our own API setup process if we know how so we can add them as we see fit for anything from weather APIs to YouTube, Twitter, etc.

**Comment by WeiseCreations** [comment]
Really social media API should be added. I think this would be extremely useful.

YouTube subscribe to channel
Twitter follow account
Facebook like page

**Comment by ThePerry-2015** [comment]
This is a planned feature down the road. :) Plugin support for own or community created plugins to use for other games or other APIs.

But what you are asking about using the interactive system to send your viewers to these functions on other sites isn't something that would be possible as I wrote to you on the Beam Community Discord since the interactive system runs on the streamers end, not on the viewers end so there wouldn't be anyway to get the inputs necessary to redirect them to the sites.

This would be something that a chat/mod bot could do through commands instead. And those commands could be triggered by the interactive buttons as well as commands in the chat. But they will, in the current interactive version, not be able to address the user pushing the button at the same level as when a user writes a command in chat which triggers the chat/mod bot which then outputs the URL for the given site in chat addressed to the user doing the command in chat.

**Comment by WeiseCreations** [comment]
Right, once you said it I thought about how it would basically require me to inject on the viewer side to have a popup or something for auth into YouTube/etc and then subscribe them.

Thank you! Maybe 2.0 can do it, haha.

**Comment by Firebottle** [comment]
Yeah, something like that would need to be done via chat (which would be better than a popup anyway). Interactive will almost certainly not cause popups on the Beam site for anyone even with 2.0 just for user experience reasons.
